name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BuildConfig: Release
  SolutionFile: ../ActivityTracker/ActivityTracker.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: dir
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      working-directory: ./ActivityTracker
      run: dotnet build --configuration ${{ env.BuildConfig }} --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
