name: GenerateDocumentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
      - name: Install dependencies
        working-directory: ./ActivityTracker
        run: dotnet restore
      - name: DocFX Build
        working-directory: ./Documentation
        run: docfx docfx.json
        continue-on-error: false
